site_name: Projetos Platforms, Microservices, DevOps and APIs - 2025.1
site_author: Henrique Turco Gera
theme:
  name: material
  language: pt
  features:
    - navigation.top
    - content.code.copy
    - navigation.path

nav:
  - Início: index.md
  - Projeto em Grupo: projeto.md
  - Projeto Inidividual:
      - Exchange API: individual/exchange.md
      - Product API: individual/product.md
      - Order API: individual/order.md
      - Jenkins: individual/jenkins.md
      - Minikube: individual/minikube.md

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.tasklist
  - tables

plugins:
  - search
